/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FireDeptWorkArea;

/**
 *
 * @author kichl
 */
public class FireDeptWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form FireDeptWorkArea
     */
    public FireDeptWorkArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        HospitaljScrollPane = new javax.swing.JScrollPane();
        workRequestTable = new javax.swing.JTable();
        acceptDispatchBtn = new javax.swing.JButton();
        DeniedDispatchBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 56, 82));
        jLabel1.setText("Fire Department Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        workRequestTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        workRequestTable.setForeground(new java.awt.Color(25, 56, 82));
        workRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Disaster Type ", "Location", "Casuality", "Status", "Reported By", "Organization", "Network", "Occurence Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        HospitaljScrollPane.setViewportView(workRequestTable);

        add(HospitaljScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 770, 110));

        acceptDispatchBtn.setBackground(new java.awt.Color(255, 255, 255));
        acceptDispatchBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        acceptDispatchBtn.setForeground(new java.awt.Color(25, 56, 82));
        acceptDispatchBtn.setText("Accepted");
        acceptDispatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptDispatchBtnActionPerformed(evt);
            }
        });
        add(acceptDispatchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 140, -1));

        DeniedDispatchBtn.setBackground(new java.awt.Color(255, 255, 255));
        DeniedDispatchBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DeniedDispatchBtn.setForeground(new java.awt.Color(25, 56, 82));
        DeniedDispatchBtn.setText("Denied");
        DeniedDispatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeniedDispatchBtnActionPerformed(evt);
            }
        });
        add(DeniedDispatchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 140, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/FireDeptWorkArea/firedeptworkarea.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void acceptDispatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptDispatchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptDispatchBtnActionPerformed

    private void DeniedDispatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeniedDispatchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeniedDispatchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeniedDispatchBtn;
    private javax.swing.JScrollPane HospitaljScrollPane;
    private javax.swing.JButton acceptDispatchBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable workRequestTable;
    // End of variables declaration//GEN-END:variables
}
