/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Volunteer;

/**
 *
 * @author kichl
 */
public class VolunteerRegisterationForm extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerWorkArea
     */
    public VolunteerRegisterationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolunteeringFormHeaderjLabel = new javax.swing.JLabel();
        NamejLabel = new javax.swing.JLabel();
        NameJField = new javax.swing.JTextField();
        AreaofInterest = new javax.swing.JTextField();
        EmailjLabel = new javax.swing.JLabel();
        UsernamejLabel = new javax.swing.JLabel();
        userNameJfield = new javax.swing.JTextField();
        passwordjLabel = new javax.swing.JLabel();
        passwordJfield = new javax.swing.JTextField();
        VolunteeringareaofInterestjLabel = new javax.swing.JLabel();
        emailJField = new javax.swing.JTextField();
        statejLabel = new javax.swing.JLabel();
        stateJField = new javax.swing.JTextField();
        CityjLabel = new javax.swing.JLabel();
        cityJField = new javax.swing.JTextField();
        CountryjLabel = new javax.swing.JLabel();
        PhoneCodejTextField = new javax.swing.JTextField();
        PhonejTextField = new javax.swing.JTextField();
        RegisterjButton = new javax.swing.JButton();
        PhonejLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        AvailbiltyjLabel = new javax.swing.JLabel();
        countryJfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VolunteeringFormHeaderjLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        VolunteeringFormHeaderjLabel.setForeground(new java.awt.Color(25, 56, 82));
        VolunteeringFormHeaderjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VolunteeringFormHeaderjLabel.setText("Volunteer Registration Form");
        add(VolunteeringFormHeaderjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        NamejLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        NamejLabel.setForeground(new java.awt.Color(25, 56, 82));
        NamejLabel.setText("Name");
        add(NamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 60, 20));

        NameJField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        NameJField.setForeground(new java.awt.Color(25, 56, 82));
        NameJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameJFieldActionPerformed(evt);
            }
        });
        NameJField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameJFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameJFieldKeyTyped(evt);
            }
        });
        add(NameJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 250, 20));

        AreaofInterest.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        AreaofInterest.setForeground(new java.awt.Color(25, 56, 82));
        AreaofInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaofInterestActionPerformed(evt);
            }
        });
        AreaofInterest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AreaofInterestKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AreaofInterestKeyTyped(evt);
            }
        });
        add(AreaofInterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 250, 20));

        EmailjLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        EmailjLabel.setForeground(new java.awt.Color(25, 56, 82));
        EmailjLabel.setText("Email");
        add(EmailjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 50, -1));

        UsernamejLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        UsernamejLabel.setForeground(new java.awt.Color(25, 56, 82));
        UsernamejLabel.setText("Username");
        add(UsernamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        userNameJfield.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        userNameJfield.setForeground(new java.awt.Color(25, 56, 82));
        userNameJfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJfieldActionPerformed(evt);
            }
        });
        userNameJfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameJfieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userNameJfieldKeyTyped(evt);
            }
        });
        add(userNameJfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 250, 20));

        passwordjLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        passwordjLabel.setForeground(new java.awt.Color(25, 56, 82));
        passwordjLabel.setText("Password");
        add(passwordjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        passwordJfield.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        passwordJfield.setForeground(new java.awt.Color(25, 56, 82));
        passwordJfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJfieldActionPerformed(evt);
            }
        });
        passwordJfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordJfieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordJfieldKeyTyped(evt);
            }
        });
        add(passwordJfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 250, 20));

        VolunteeringareaofInterestjLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        VolunteeringareaofInterestjLabel.setForeground(new java.awt.Color(25, 56, 82));
        VolunteeringareaofInterestjLabel.setText("Voluntering area of Interest");
        add(VolunteeringareaofInterestjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, 20));

        emailJField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        emailJField.setForeground(new java.awt.Color(25, 56, 82));
        emailJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJFieldActionPerformed(evt);
            }
        });
        emailJField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailJFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailJFieldKeyTyped(evt);
            }
        });
        add(emailJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 250, 20));

        statejLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        statejLabel.setForeground(new java.awt.Color(25, 56, 82));
        statejLabel.setText("State");
        add(statejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, 20));

        stateJField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        stateJField.setForeground(new java.awt.Color(25, 56, 82));
        stateJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateJFieldActionPerformed(evt);
            }
        });
        stateJField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stateJFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stateJFieldKeyTyped(evt);
            }
        });
        add(stateJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 250, 20));

        CityjLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        CityjLabel.setForeground(new java.awt.Color(25, 56, 82));
        CityjLabel.setText("City");
        add(CityjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, 20));

        cityJField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cityJField.setForeground(new java.awt.Color(25, 56, 82));
        cityJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJFieldActionPerformed(evt);
            }
        });
        cityJField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityJFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityJFieldKeyTyped(evt);
            }
        });
        add(cityJField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 250, 20));

        CountryjLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        CountryjLabel.setForeground(new java.awt.Color(25, 56, 82));
        CountryjLabel.setText("Country");
        add(CountryjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, 20));
        add(PhoneCodejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 50, -1));
        add(PhonejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 190, -1));

        RegisterjButton.setText("Register");
        add(RegisterjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 100, 40));

        PhonejLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        PhonejLabel.setForeground(new java.awt.Color(25, 56, 82));
        PhonejLabel.setText("Phone No");
        add(PhonejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 250, -1));

        AvailbiltyjLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        AvailbiltyjLabel.setForeground(new java.awt.Color(25, 56, 82));
        AvailbiltyjLabel.setText("Avalibility");
        add(AvailbiltyjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, 20));

        countryJfield.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        countryJfield.setForeground(new java.awt.Color(25, 56, 82));
        countryJfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryJfieldActionPerformed(evt);
            }
        });
        countryJfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                countryJfieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                countryJfieldKeyTyped(evt);
            }
        });
        add(countryJfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 250, 20));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/volunteering_form.PNG"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void AreaofInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaofInterestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaofInterestActionPerformed

    private void AreaofInterestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AreaofInterestKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaofInterestKeyPressed

    private void AreaofInterestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AreaofInterestKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AreaofInterestKeyTyped

    private void NameJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameJFieldActionPerformed

    private void NameJFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameJFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameJFieldKeyPressed

    private void NameJFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameJFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NameJFieldKeyTyped

    private void userNameJfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJfieldActionPerformed

    private void userNameJfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameJfieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJfieldKeyPressed

    private void userNameJfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameJfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJfieldKeyTyped

    private void passwordJfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJfieldActionPerformed

    private void passwordJfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordJfieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJfieldKeyPressed

    private void passwordJfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordJfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJfieldKeyTyped

    private void emailJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJFieldActionPerformed

    private void emailJFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailJFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJFieldKeyPressed

    private void emailJFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailJFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJFieldKeyTyped

    private void stateJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateJFieldActionPerformed

    private void stateJFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateJFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateJFieldKeyPressed

    private void stateJFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateJFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_stateJFieldKeyTyped

    private void cityJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJFieldActionPerformed

    private void cityJFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityJFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJFieldKeyPressed

    private void cityJFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityJFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJFieldKeyTyped

    private void countryJfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryJfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryJfieldActionPerformed

    private void countryJfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryJfieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryJfieldKeyPressed

    private void countryJfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryJfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_countryJfieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaofInterest;
    private javax.swing.JLabel AvailbiltyjLabel;
    private javax.swing.JLabel CityjLabel;
    private javax.swing.JLabel CountryjLabel;
    private javax.swing.JLabel EmailjLabel;
    private javax.swing.JTextField NameJField;
    private javax.swing.JLabel NamejLabel;
    private javax.swing.JTextField PhoneCodejTextField;
    private javax.swing.JLabel PhonejLabel;
    private javax.swing.JTextField PhonejTextField;
    private javax.swing.JButton RegisterjButton;
    private javax.swing.JLabel UsernamejLabel;
    private javax.swing.JLabel VolunteeringFormHeaderjLabel;
    private javax.swing.JLabel VolunteeringareaofInterestjLabel;
    private javax.swing.JTextField cityJField;
    private javax.swing.JTextField countryJfield;
    private javax.swing.JTextField emailJField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JTextField passwordJfield;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JTextField stateJField;
    private javax.swing.JLabel statejLabel;
    private javax.swing.JTextField userNameJfield;
    // End of variables declaration//GEN-END:variables
}
