/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import javax.swing.JPanel;

/**
 *
 * @author rtspi
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminJPanel = new javax.swing.JPanel();
        leftSystemPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnManageNetwork = new javax.swing.JButton();
        btnManageEnterprises = new javax.swing.JButton();
        btnManageEnterpriseAdmins = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        rightSystemPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        adminJPanel.setPreferredSize(new java.awt.Dimension(1300, 800));

        leftSystemPanel.setBackground(new java.awt.Color(0, 0, 0));
        leftSystemPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Manage Network");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        leftSystemPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 30));

        btnManageNetwork.setBackground(new java.awt.Color(0, 0, 0));
        btnManageNetwork.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageNetwork.setForeground(new java.awt.Color(102, 102, 102));
        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        leftSystemPanel.add(btnManageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 30));

        btnManageEnterprises.setBackground(new java.awt.Color(0, 0, 0));
        btnManageEnterprises.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageEnterprises.setForeground(new java.awt.Color(102, 102, 102));
        btnManageEnterprises.setText("Manage Enterprises");
        btnManageEnterprises.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageEnterprises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterprisesActionPerformed(evt);
            }
        });
        leftSystemPanel.add(btnManageEnterprises, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 30));

        btnManageEnterpriseAdmins.setBackground(new java.awt.Color(0, 0, 0));
        btnManageEnterpriseAdmins.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnManageEnterpriseAdmins.setForeground(new java.awt.Color(102, 102, 102));
        btnManageEnterpriseAdmins.setText("Manage Enterprise Admins");
        btnManageEnterpriseAdmins.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageEnterpriseAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseAdminsActionPerformed(evt);
            }
        });
        leftSystemPanel.add(btnManageEnterpriseAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("Manage Network");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        leftSystemPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, 30));
        leftSystemPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, 250, 10));

        jTree1.setBackground(new java.awt.Color(0, 0, 0));
        jTree1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jTree1.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jTree1);

        leftSystemPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 190, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Selected Node:");
        leftSystemPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, 30));

        rightSystemPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout adminJPanelLayout = new javax.swing.GroupLayout(adminJPanel);
        adminJPanel.setLayout(adminJPanelLayout);
        adminJPanelLayout.setHorizontalGroup(
            adminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminJPanelLayout.createSequentialGroup()
                .addComponent(leftSystemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightSystemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE))
        );
        adminJPanelLayout.setVerticalGroup(
            adminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftSystemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
            .addComponent(rightSystemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(adminJPanel, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageEnterprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterprisesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageEnterprisesActionPerformed

    private void btnManageEnterpriseAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseAdminsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageEnterpriseAdminsActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminJPanel;
    private javax.swing.JButton btnManageEnterpriseAdmins;
    private javax.swing.JButton btnManageEnterprises;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPanel leftSystemPanel;
    private javax.swing.JPanel rightSystemPanel;
    // End of variables declaration//GEN-END:variables
}
