/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RecoveryUnit;

/**
 *
 * @author kichl
 */
public class CreateRecoveryUnitUserAdmin extends javax.swing.JPanel {

    /**
     * Creates new form CreateRecoveryUnitUserAdmin
     */
    public CreateRecoveryUnitUserAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtName3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        enterpriseJTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Recovery Unit Admin Screen");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 21, 276, 30));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 116, 50, 20));

        txtName.setToolTipText("Name");
        txtName.setDoubleBuffered(true);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 115, 160, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("UserName:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 80, 20));

        txtName1.setToolTipText("Name");
        txtName1.setDoubleBuffered(true);
        add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 160, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Password :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 80, 20));

        txtName2.setToolTipText("Name");
        txtName2.setDoubleBuffered(true);
        add(txtName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 115, 160, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("Organisation:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 100, 20));

        txtName3.setToolTipText("Name");
        txtName3.setDoubleBuffered(true);
        add(txtName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 115, 160, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("Enterprise :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 80, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 160, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setText("Network :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 80, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 160, -1));

        jToggleButton1.setText("Create");
        add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 118, -1));

        enterpriseJTable1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        enterpriseJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Username", "Organisation", "Enterprise Name", "Network"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(enterpriseJTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 670, 95));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/RecoveryUnit/diasterunitcreateuser.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 1030, 530));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable enterpriseJTable1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtName3;
    // End of variables declaration//GEN-END:variables
}
