/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicalWorkArea;

/**
 *
 * @author kichl
 */
public class HospitalWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form HospitalWorkArea
     */
    public HospitalWorkArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        HospitaljScrollPane = new javax.swing.JScrollPane();
        workRequestTable = new javax.swing.JTable();
        acceptReqBtn1 = new javax.swing.JButton();
        rejectreqBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 56, 82));
        jLabel1.setText("Hospital Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        workRequestTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        workRequestTable.setForeground(new java.awt.Color(25, 56, 82));
        workRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Disaster Type ", "Location", "Casuality", "Status", "Reported By", "Organization", "Network", "Occurence Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        HospitaljScrollPane.setViewportView(workRequestTable);

        add(HospitaljScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 780, 110));

        acceptReqBtn1.setBackground(new java.awt.Color(255, 255, 255));
        acceptReqBtn1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        acceptReqBtn1.setForeground(new java.awt.Color(25, 56, 82));
        acceptReqBtn1.setText("Accepted");
        acceptReqBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptReqBtn1ActionPerformed(evt);
            }
        });
        add(acceptReqBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 170, -1));

        rejectreqBtn.setBackground(new java.awt.Color(255, 255, 255));
        rejectreqBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        rejectreqBtn.setForeground(new java.awt.Color(25, 56, 82));
        rejectreqBtn.setText("Denied");
        rejectreqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectreqBtnActionPerformed(evt);
            }
        });
        add(rejectreqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 170, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/MedicalWorkArea/hospitalwrkareapanel.PNG"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1210, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void acceptReqBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptReqBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptReqBtn1ActionPerformed

    private void rejectreqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectreqBtnActionPerformed

    }//GEN-LAST:event_rejectreqBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane HospitaljScrollPane;
    private javax.swing.JButton acceptReqBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton rejectreqBtn;
    private javax.swing.JTable workRequestTable;
    // End of variables declaration//GEN-END:variables
}
